Collecting a log 1st draft
AdguardTeam/AdGuardVpnKnowledgeBase pull request #2
Opened 2020-10-01 15:20 UTC by printstr

Article on how to collect a log on AG VPN
1. Debug log
2.Added screenshots
3. Link to logcat article

2020-10-02 11:25 UTC, vbagirov requested changes

2020-10-02 11:25 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +* [How to collect a debug log?](#debug)
В принципе, если всего 1 пункт, то не обязательно делать ToC, но можно и оставить, раз уж сделал.

2020-10-02 11:25 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +Sometimes in order to understand a problem and fix it we need to collect **log files**, or **logs**. Basically, these files contain information about the program and it's work.
it's -- тут точно нужен апостроф? Вроде "its" в данном случае

2020-10-02 11:25 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +3. Go to "Logging level" and Choose "Trace" tab with "Record everything" below. It's desirable to close all background apps that don't concern the problem beforehand.
choose с маленькой

2020-10-02 11:25 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +3. Go to "Logging level" and Choose "Trace" tab with "Record everything" below. It's desirable to close all background apps that don't concern the problem beforehand.
мне кажется, тут не совсем `tab`, скорее `mode` или что-то в таком духе. И ещё мне кажется про "Record everything" лишнее уточнение. И так однозначно понятно, о чем речь.

2020-10-02 11:25 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +4. Reproduce the problem and set the logging level back to "Info" with "Default logging level". Note down the exact time when it happened.
Аналогично, мне кажется достаточно так:
"Reproduce the problem and set the logging level back to "Info". Note down the exact time when it happened."

2020-10-02 11:25 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +5. Send us a message from program by choosing "Report a bug" in the "Settings" menu. Don't forget to check the "Send detailed system info" checkbox under the text field and to include the timestamp f
на андроиде мы приложения называем apps или applications, а не programs

2020-10-02 11:25 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +As an alternative, you can export the logs (along with the *state.txt* file that contains system information and information about AdGuard settings) directly into a local file. It can be convenient,
точки в конце абзаца не хватает

2020-10-02 11:25 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +Another way of collecting logs is to do it with logcat. Read more about logcat [here](add link)
ссылку забыл добавить, видимо (и тоже точки в конце нет).

2020-10-02 11:25 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +<br>
а для чего бры?

2020-10-02 11:26 UTC, printstr commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +Sometimes in order to understand a problem and fix it we need to collect **log files**, or **logs**. Basically, these files contain information about the program and it's work.
точняк

2020-10-02 11:27 UTC, printstr commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +Another way of collecting logs is to do it with logcat. Read more about logcat [here](add link)
а какая там ссылка в итоге?

2020-10-02 11:27 UTC, printstr commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +<br>
уберем

2020-10-05 15:29 UTC, vbagirov requested changes

2020-10-05 15:29 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +title: 'Collecting a log on AdGuard VPN for Android'
а почему тут `on`? Вроде в приложении же

2020-10-05 15:29 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.en.md
> +Another way of collecting logs is to do it with logcat. Read more about logcat [here](https://kb.adguard-vpn.com/en/android-vpn/solving-problems/logcat).
Это вроде не совсем так. Логкат собирает другие логи. Так что эту фразу можно убрать.

2020-10-05 15:29 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.en.md
> +title: 'Compatibility mode AdGuard VPN and ad blocker for Android'
тайтл кривоват, надо поправить

2020-10-05 15:29 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.en.md
> +# AdGuard VPN and ad blocker: Compatibility mode
лучше AdGuard VPN and AdGuard ad blocker: Compatibility mode

2020-10-05 15:29 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.en.md
> +Starting from the [version 3.5](https://adguard.com/en/blog/adguard-3-5-for-android.html) AdGuard ad blocker will have compatibility mode with AdGuard VPN. The moment you have both apps installed, yo
почему will have? версия уже вышла

2020-10-05 15:29 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +title: 'AdGuard VPN для Android режим совместимости с блокировщиком'
тоже тайтл кривой

2020-10-05 15:29 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.en.md
> +and choose VPN or Proxy mode and press “Unlink” button
тут название режима наверное надо в кавычки

2020-10-05 15:29 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.en.md
> +If for some reason you would like to turn Compatibility Mode off, just go to “Settings” - “Advanced settings” - “Operating mode”
здесь и далее почему-то кавычки не такие, как в статье про логи

2020-10-06 09:50 UTC, vbagirov requested changes

2020-10-06 09:50 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.en.md
> +Starting from the [version 3.5](https://adguard.com/en/blog/adguard-3-5-for-android.html) AdGuard ad blocker has compatibility mode with AdGuard VPN. The moment you have both apps installed, you rece
я погуглил, кажется, starting with корректнее

2020-10-06 09:50 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.en.md
> +title: 'AdGuard VPN and AdGuard ad blocker: Compatibility mode'
Давай тупо сделаем "Compatibility mode with AdGuard ad blocker"
И так ясно что речь про VPN, это же в разделе про впн. А так будет почище тайтл чутка

2020-10-06 09:50 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +title: 'AdGuard VPN и блокировщик рекламы AdGuard: Режим совместимости'
аналогично, см. коммент к англ тайтлу

2020-10-06 16:30 UTC, vbagirov requested changes

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +Иногда чтобы понять и исправить ошибку нам необходимо собирать **файлы лога** или **логи**. Проще говоря, это файлы в которых содержится информация о самом приложении и его работе.
почти уверен, что перед "чтобы" надо запятую

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +Иногда чтобы понять и исправить ошибку нам необходимо собирать **файлы лога** или **логи**. Проще говоря, это файлы в которых содержится информация о самом приложении и его работе.
"файлы журналов или логи" - "файлы лога" это совсем дичь какая-то

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +Иногда чтобы понять и исправить ошибку нам необходимо собирать **файлы лога** или **логи**. Проще говоря, это файлы в которых содержится информация о самом приложении и его работе.
перед "в которых" тоже запятая

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +2. Выберите " Расширенные настройки " в меню "Настройки".
пробелы лишние перед и после кавычек

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +3. "Уровень логгирования" переключите в режим "Записывать всё". Желательно перед этим закрыть все фоновые приложения, не связанные с проблемой.
Кажется, "Уровень логирования" - с одной "г"

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +4. Постарайтесь воспроизвести проблему, после чего уровень логгирования переключите обратно на обычный ("По умолчанию"). Заметьте точное время, когда это произошло.
"логирования"

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +Как альтернативный вариант, можно экспортировать лог-файлы (вместе с файлом *state.txt*, содержащим некоторую информацию о системе и о настройках AdGuard) напрямую в локальный файл. Это бывает удобно
"лог-файлы" тоже не очень звучит. "Логи" или "файлы журналов",

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.en.md
> +title: 'Compatibility mode with AdGuard ad blocker'
я чето тупанул тогда. Не "Compatibility mode with AdGuard ad blocker", а "'Compatibility with AdGuard ad blocker". Что думаешь?

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +title: 'Режим совместимости c блокировщиком рекламы AdGuard'
И тут может тоже просто "Совместимость с ..."?

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +Начиная с версии [3.5](https://adguard.com/ru/blog/adguard-3-5-for-android.html) блокировщик рекламы AdGuard и AdGuard VPN автоматически настраивают "Режим совместимости". Как только вы установили об
лучше в ссылку обернуть так: [версии 3.5]

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +Начиная с версии [3.5](https://adguard.com/ru/blog/adguard-3-5-for-android.html) блокировщик рекламы AdGuard и AdGuard VPN автоматически настраивают "Режим совместимости". Как только вы установили об
"пуш-уведомление" через дефис

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +Начиная с версии [3.5](https://adguard.com/ru/blog/adguard-3-5-for-android.html) блокировщик рекламы AdGuard и AdGuard VPN автоматически настраивают "Режим совместимости". Как только вы установили об
Либо "Режим совместимости включен" без кавычек, либо, если цитируешь уведомление, то не надо "о том, что".

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +Начиная с версии [3.5](https://adguard.com/ru/blog/adguard-3-5-for-android.html) блокировщик рекламы AdGuard и AdGuard VPN автоматически настраивают "Режим совместимости". Как только вы установили об
"И, собственно, все." - это лишнее в базе знаний

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +Это довольно удобная функция, так как она позволяет вам одновременно использовать все преимущества VPN сервиса и блокировщика рекламы. Приватность и защита данных в сети, да еще и без рекламы! AdGuar
VPN-сервис через дефис

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +Это довольно удобная функция, так как она позволяет вам одновременно использовать все преимущества VPN сервиса и блокировщика рекламы. Приватность и защита данных в сети, да еще и без рекламы! AdGuar
"Приватность и защита данных в сети, да еще и без рекламы!" - такие эмоциональные выражения не нужны в кб

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +Если по какой-то причине вы хотите отключить "Режим совместимости", зайдите в "Настройки" "Расширенные настройки" - "Operating mode"
"Режим совместимости"- не нужны кавычки. И с маленькой буквы можно

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +Если по какой-то причине вы хотите отключить "Режим совместимости", зайдите в "Настройки" "Расширенные настройки" - "Operating mode"
"Настройки" "Расширенные настройки" - потерялось тире

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +Если по какой-то причине вы хотите отключить "Режим совместимости", зайдите в "Настройки" "Расширенные настройки" - "Operating mode"
"Operating mode" - не переведено?

2020-10-06 16:30 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +и выберите режим "VPN" или "SOCKS5" и нажмите кнопку "Unlink".
два раза "и"

2020-10-07 09:46 UTC, printstr commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +3. "Уровень логгирования" переключите в режим "Записывать всё". Желательно перед этим закрыть все фоновые приложения, не связанные с проблемой.
с двумя

2020-10-07 12:40 UTC, vbagirov requested changes

2020-10-07 12:40 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +Иногда, чтобы понять и исправить ошибку нам необходимо собирать **файлы журналов** или **логи**. Проще говоря - это файлы, в которых содержится информация о самом приложении и его работе.
перед "нам" тоже нужна запятая. 

Тире должно быть длинным, а не дефисом: —

2020-10-07 12:40 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +Иногда, чтобы понять и исправить ошибку нам необходимо собирать **файлы журналов** или **логи**. Проще говоря - это файлы, в которых содержится информация о самом приложении и его работе.
И вместо "нам необходимо собирать" наверное лучше "нам необходимо увидеть", так более по-русски

2020-10-07 12:40 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +Начиная с [версии 3.5](https://adguard.com/ru/blog/adguard-3-5-for-android.html) блокировщик рекламы AdGuard и AdGuard VPN автоматически настраивают режим совместимости. Как только вы установили оба
пуш-уведомление

2020-10-07 12:40 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/110.log/docs.ru.md
> +3. "Уровень логгирования" переключите в режим "Записывать всё". Желательно перед этим закрыть все фоновые приложения, не связанные с проблемой.
Всё ещё не исправлено

2020-10-07 12:40 UTC, vbagirov commented on 110.android-vpn/130.solving-problems/130.compatibility/docs.ru.md
> +выберите режим "VPN" или "SOCKS5" и нажмите кнопку "Unlink".
с большой буквы

2020-10-07 12:56 UTC, vbagirov approved these changes

2020-10-07 12:56 UTC, merged